pekko {
  loggers = ["org.apache.pekko.event.slf4j.Slf4jLogger"]
  logging-filter = "org.apache.pekko.event.slf4j.Slf4jLoggingFilter"
  loglevel = "WARN"
  loglevel = ${?pekko.loglevel}
  log-config-on-start = off

  http {
    server {
      idle-timeout = infinite
      request-timeout = infinite
    }
  }
}
